import React from "react";
import { useState } from "react";

function PointsTable() {
  let pointsTableData = {
    pointsTable: [
      {
        groupName: "Teams",
        pointsTableInfo: [
          {
            teamId: 63,
            teamName: "KKR",
            matchesPlayed: 14,
            matchesWon: 9,
            matchesLost: 3,
            noRes: 2,
            points: 20,
            nrr: "+1.428",
            teamFullName: "Kolkata Knight Riders",
            teamMatches: [
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1711202400000",
                result: "Won by 4 runs",
                opponentSName: "SRH",
                matchId: 89665,
                matchName: "3rd Match",
                winner: 63,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1711720800000",
                result: "Won by 7 wkts",
                opponentSName: "RCB",
                matchId: 89703,
                matchName: "10th Match",
                winner: 63,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1712152800000",
                result: "Won by 106 runs",
                opponentSName: "DC",
                matchId: 89745,
                matchName: "16th Match",
                winner: 63,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1712584800000",
                result: "Lost by 7 wkts",
                opponentSName: "CSK",
                matchId: 91380,
                matchName: "22nd Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1713088800000",
                result: "Won by 8 wkts",
                opponentSName: "LSG",
                matchId: 91420,
                matchName: "28th Match",
                winner: 63,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1713276000000",
                result: "Lost by 2 wkts",
                opponentSName: "RR",
                matchId: 91443,
                matchName: "31st Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1713693600000",
                result: "Won by 1 run",
                opponentSName: "RCB",
                matchId: 91479,
                matchName: "36th Match",
                winner: 63,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1714140000000",
                result: "Lost by 8 wkts",
                opponentSName: "PBKS",
                matchId: 91528,
                matchName: "42nd Match",
                winner: 65,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1714399200000",
                result: "Won by 7 wkts",
                opponentSName: "DC",
                matchId: 91564,
                matchName: "47th Match",
                winner: 63,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1714744800000",
                result: "Won by 24 runs",
                opponentSName: "MI",
                matchId: 91596,
                matchName: "51st Match",
                winner: 63,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1714917600000",
                result: "Won by 98 runs",
                opponentSName: "LSG",
                matchId: 91618,
                matchName: "54th Match",
                winner: 63,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1715436000000",
                result: "Won by 18 runs - 16 overs game - due to rain",
                opponentSName: "MI",
                matchId: 91654,
                matchName: "60th Match",
                winner: 63,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1715608800000",
                result: "Match abandoned without toss",
                opponentSName: "GT",
                matchId: 91677,
                matchName: "63rd Match",
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1716127200000",
                result: "Match abandoned due to rain (with toss)",
                opponentSName: "RR",
                matchId: 91717,
                matchName: "70th Match",
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1716300000000",
                result: "Won by 8 wkts",
                opponentSName: "SRH",
                matchId: 91722,
                matchName: "Qualifier 1",
                winner: 63,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1716732000000",
                result: "Won by 8 wkts",
                opponentSName: "SRH",
                matchId: 91740,
                matchName: "Final",
                winner: 63,
                opponentId: 255,
                opponentImageId: 225649,
              },
            ],
            form: ["W", "A", "A", "W", "W"],
            teamImageId: 225646,
            teamQualifyStatus: "Q",
          },
          {
            teamId: 255,
            teamName: "SRH",
            matchesPlayed: 14,
            matchesWon: 8,
            matchesLost: 5,
            noRes: 1,
            points: 17,
            nrr: "+0.414",
            teamFullName: "Sunrisers Hyderabad",
            teamMatches: [
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1711202400000",
                result: "Lost by 4 runs",
                opponentSName: "KKR",
                matchId: 89665,
                matchName: "3rd Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1711548000000",
                result: "Won by 31 runs",
                opponentSName: "MI",
                matchId: 89693,
                matchName: "8th Match",
                winner: 255,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1711879200000",
                result: "Lost by 7 wkts",
                opponentSName: "GT",
                matchId: 89717,
                matchName: "12th Match",
                winner: 971,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1712325600000",
                result: "Won by 6 wkts",
                opponentSName: "CSK",
                matchId: 89752,
                matchName: "18th Match",
                winner: 255,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1712671200000",
                result: "Won by 2 runs",
                opponentSName: "PBKS",
                matchId: 91389,
                matchName: "23rd Match",
                winner: 255,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1713189600000",
                result: "Won by 25 runs",
                opponentSName: "RCB",
                matchId: 91434,
                matchName: "30th Match",
                winner: 255,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1713621600000",
                result: "Won by 67 runs",
                opponentSName: "DC",
                matchId: 91474,
                matchName: "35th Match",
                winner: 255,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1714053600000",
                result: "Lost by 35 runs",
                opponentSName: "RCB",
                matchId: 91524,
                matchName: "41st Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1714312800000",
                result: "Lost by 78 runs",
                opponentSName: "CSK",
                matchId: 91555,
                matchName: "46th Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1714658400000",
                result: "Won by 1 run",
                opponentSName: "RR",
                matchId: 91587,
                matchName: "50th Match",
                winner: 255,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1715004000000",
                result: "Lost by 7 wkts",
                opponentSName: "MI",
                matchId: 91623,
                matchName: "55th Match",
                winner: 62,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1715176800000",
                result: "Won by 10 wkts",
                opponentSName: "LSG",
                matchId: 91641,
                matchName: "57th Match",
                winner: 255,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1715868000000",
                result: "Match abandoned without toss",
                opponentSName: "GT",
                matchId: 91690,
                matchName: "66th Match",
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1716112800000",
                result: "Won by 4 wkts",
                opponentSName: "PBKS",
                matchId: 91713,
                matchName: "69th Match",
                winner: 255,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1716300000000",
                result: "Lost by 8 wkts",
                opponentSName: "KKR",
                matchId: 91722,
                matchName: "Qualifier 1",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1716559200000",
                result: "Won by 36 runs",
                opponentSName: "RR",
                matchId: 91735,
                matchName: "Qualifier 2",
                winner: 255,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1716732000000",
                result: "Lost by 8 wkts",
                opponentSName: "KKR",
                matchId: 91740,
                matchName: "Final",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
            ],
            form: ["A", "W", "L", "W", "L"],
            teamImageId: 225649,
            teamQualifyStatus: "Q",
          },
          {
            teamId: 64,
            teamName: "RR",
            matchesPlayed: 14,
            matchesWon: 8,
            matchesLost: 5,
            noRes: 1,
            points: 17,
            nrr: "+0.273",
            teamFullName: "Rajasthan Royals",
            teamMatches: [
              {
                opponent: "Lucknow Super Giants",
                startdt: "1711274400000",
                result: "Won by 20 runs",
                opponentSName: "LSG",
                matchId: 89668,
                matchName: "4th Match",
                winner: 64,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1711634400000",
                result: "Won by 12 runs",
                opponentSName: "DC",
                matchId: 89700,
                matchName: "9th Match",
                winner: 64,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1711980000000",
                result: "Won by 6 wkts",
                opponentSName: "MI",
                matchId: 89731,
                matchName: "14th Match",
                winner: 64,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1712412000000",
                result: "Won by 6 wkts",
                opponentSName: "RCB",
                matchId: 89756,
                matchName: "19th Match",
                winner: 64,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1712757600000",
                result: "Lost by 3 wkts",
                opponentSName: "GT",
                matchId: 91393,
                matchName: "24th Match",
                winner: 971,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1713016800000",
                result: "Won by 3 wkts",
                opponentSName: "PBKS",
                matchId: 91416,
                matchName: "27th Match",
                winner: 64,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1713276000000",
                result: "Won by 2 wkts",
                opponentSName: "KKR",
                matchId: 91443,
                matchName: "31st Match",
                winner: 64,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1713794400000",
                result: "Won by 9 wkts",
                opponentSName: "MI",
                matchId: 91497,
                matchName: "38th Match",
                winner: 64,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1714226400000",
                result: "Won by 7 wkts",
                opponentSName: "LSG",
                matchId: 91542,
                matchName: "44th Match",
                winner: 64,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1714658400000",
                result: "Lost by 1 run",
                opponentSName: "SRH",
                matchId: 91587,
                matchName: "50th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1715090400000",
                result: "Lost by 20 runs",
                opponentSName: "DC",
                matchId: 91632,
                matchName: "56th Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1715508000000",
                result: "Lost by 5 wkts",
                opponentSName: "CSK",
                matchId: 91663,
                matchName: "61st Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1715781600000",
                result: "Lost by 5 wkts",
                opponentSName: "PBKS",
                matchId: 91686,
                matchName: "65th Match",
                winner: 65,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1716127200000",
                result: "Match abandoned due to rain (with toss)",
                opponentSName: "KKR",
                matchId: 91717,
                matchName: "70th Match",
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1716386400000",
                result: "Won by 4 wkts",
                opponentSName: "RCB",
                matchId: 91731,
                matchName: "Eliminator",
                winner: 64,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1716559200000",
                result: "Lost by 36 runs",
                opponentSName: "SRH",
                matchId: 91735,
                matchName: "Qualifier 2",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
            ],
            form: ["L", "L", "A", "W", "L"],
            teamImageId: 225647,
            teamQualifyStatus: "Q",
          },
          {
            teamId: 59,
            teamName: "RCB",
            matchesPlayed: 14,
            matchesWon: 7,
            matchesLost: 7,
            points: 14,
            nrr: "+0.459",
            teamFullName: "Royal Challengers Bengaluru",
            teamMatches: [
              {
                opponent: "Chennai Super Kings",
                startdt: "1711117800000",
                result: "Lost by 6 wkts",
                opponentSName: "CSK",
                matchId: 89654,
                matchName: "1st Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1711375200000",
                result: "Won by 4 wkts",
                opponentSName: "PBKS",
                matchId: 89682,
                matchName: "6th Match",
                winner: 59,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1711720800000",
                result: "Lost by 7 wkts",
                opponentSName: "KKR",
                matchId: 89703,
                matchName: "10th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1712066400000",
                result: "Lost by 28 runs",
                opponentSName: "LSG",
                matchId: 89738,
                matchName: "15th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1712412000000",
                result: "Lost by 6 wkts",
                opponentSName: "RR",
                matchId: 89756,
                matchName: "19th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1712844000000",
                result: "Lost by 7 wkts",
                opponentSName: "MI",
                matchId: 91398,
                matchName: "25th Match",
                winner: 62,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1713189600000",
                result: "Lost by 25 runs",
                opponentSName: "SRH",
                matchId: 91434,
                matchName: "30th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1713693600000",
                result: "Lost by 1 run",
                opponentSName: "KKR",
                matchId: 91479,
                matchName: "36th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1714053600000",
                result: "Won by 35 runs",
                opponentSName: "SRH",
                matchId: 91524,
                matchName: "41st Match",
                winner: 59,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1714298400000",
                result: "Won by 9 wkts",
                opponentSName: "GT",
                matchId: 91551,
                matchName: "45th Match",
                winner: 59,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1714831200000",
                result: "Won by 4 wkts",
                opponentSName: "GT",
                matchId: 91600,
                matchName: "52nd Match",
                winner: 59,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1715263200000",
                result: "Won by 60 runs",
                opponentSName: "PBKS",
                matchId: 91645,
                matchName: "58th Match",
                winner: 59,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1715522400000",
                result: "Won by 47 runs",
                opponentSName: "DC",
                matchId: 91668,
                matchName: "62nd Match",
                winner: 59,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1716040800000",
                result: "Won by 27 runs",
                opponentSName: "CSK",
                matchId: 91704,
                matchName: "68th Match",
                winner: 59,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1716386400000",
                result: "Lost by 4 wkts",
                opponentSName: "RR",
                matchId: 91731,
                matchName: "Eliminator",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
            ],
            form: ["W", "W", "W", "W", "L"],
            teamImageId: 225643,
            teamQualifyStatus: "Q",
          },
          {
            teamId: 58,
            teamName: "CSK",
            matchesPlayed: 14,
            matchesWon: 7,
            matchesLost: 7,
            points: 14,
            nrr: "+0.392",
            teamFullName: "Chennai Super Kings",
            teamMatches: [
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1711117800000",
                result: "Won by 6 wkts",
                opponentSName: "RCB",
                matchId: 89654,
                matchName: "1st Match",
                winner: 58,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1711461600000",
                result: "Won by 63 runs",
                opponentSName: "GT",
                matchId: 89689,
                matchName: "7th Match",
                winner: 58,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1711893600000",
                result: "Lost by 20 runs",
                opponentSName: "DC",
                matchId: 89724,
                matchName: "13th Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1712325600000",
                result: "Lost by 6 wkts",
                opponentSName: "SRH",
                matchId: 89752,
                matchName: "18th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1712584800000",
                result: "Won by 7 wkts",
                opponentSName: "KKR",
                matchId: 91380,
                matchName: "22nd Match",
                winner: 58,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1713103200000",
                result: "Won by 20 runs",
                opponentSName: "MI",
                matchId: 91425,
                matchName: "29th Match",
                winner: 58,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1713535200000",
                result: "Lost by 8 wkts",
                opponentSName: "LSG",
                matchId: 91470,
                matchName: "34th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1713880800000",
                result: "Lost by 6 wkts",
                opponentSName: "LSG",
                matchId: 91506,
                matchName: "39th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1714312800000",
                result: "Won by 78 runs",
                opponentSName: "SRH",
                matchId: 91555,
                matchName: "46th Match",
                winner: 58,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1714572000000",
                result: "Lost by 7 wkts",
                opponentSName: "PBKS",
                matchId: 91578,
                matchName: "49th Match",
                winner: 65,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1714903200000",
                result: "Won by 28 runs",
                opponentSName: "PBKS",
                matchId: 91609,
                matchName: "53rd Match",
                winner: 58,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1715349600000",
                result: "Lost by 35 runs",
                opponentSName: "GT",
                matchId: 91650,
                matchName: "59th Match",
                winner: 971,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1715508000000",
                result: "Won by 5 wkts",
                opponentSName: "RR",
                matchId: 91663,
                matchName: "61st Match",
                winner: 58,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1716040800000",
                result: "Lost by 27 runs",
                opponentSName: "RCB",
                matchId: 91704,
                matchName: "68th Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
            ],
            form: ["L", "W", "L", "W", "L"],
            teamImageId: 225641,
            teamQualifyStatus: "E",
          },
          {
            teamId: 61,
            teamName: "DC",
            matchesPlayed: 14,
            matchesWon: 7,
            matchesLost: 7,
            points: 14,
            nrr: "-0.377",
            teamFullName: "Delhi Capitals",
            teamMatches: [
              {
                opponent: "Punjab Kings",
                startdt: "1711188000000",
                result: "Lost by 4 wkts",
                opponentSName: "PBKS",
                matchId: 89661,
                matchName: "2nd Match",
                winner: 65,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1711634400000",
                result: "Lost by 12 runs",
                opponentSName: "RR",
                matchId: 89700,
                matchName: "9th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1711893600000",
                result: "Won by 20 runs",
                opponentSName: "CSK",
                matchId: 89724,
                matchName: "13th Match",
                winner: 61,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1712152800000",
                result: "Lost by 106 runs",
                opponentSName: "KKR",
                matchId: 89745,
                matchName: "16th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1712484000000",
                result: "Lost by 29 runs",
                opponentSName: "MI",
                matchId: 89763,
                matchName: "20th Match",
                winner: 62,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1712930400000",
                result: "Won by 6 wkts",
                opponentSName: "LSG",
                matchId: 91407,
                matchName: "26th Match",
                winner: 61,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1713362400000",
                result: "Won by 6 wkts",
                opponentSName: "GT",
                matchId: 91452,
                matchName: "32nd Match",
                winner: 61,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1713621600000",
                result: "Lost by 67 runs",
                opponentSName: "SRH",
                matchId: 91474,
                matchName: "35th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1713967200000",
                result: "Won by 4 runs",
                opponentSName: "GT",
                matchId: 91515,
                matchName: "40th Match",
                winner: 61,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1714212000000",
                result: "Won by 10 runs",
                opponentSName: "MI",
                matchId: 91533,
                matchName: "43rd Match",
                winner: 61,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1714399200000",
                result: "Lost by 7 wkts",
                opponentSName: "KKR",
                matchId: 91564,
                matchName: "47th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1715090400000",
                result: "Won by 20 runs",
                opponentSName: "RR",
                matchId: 91632,
                matchName: "56th Match",
                winner: 61,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1715522400000",
                result: "Lost by 47 runs",
                opponentSName: "RCB",
                matchId: 91668,
                matchName: "62nd Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1715695200000",
                result: "Won by 19 runs",
                opponentSName: "LSG",
                matchId: 91681,
                matchName: "64th Match",
                winner: 61,
                opponentId: 966,
                opponentImageId: 389444,
              },
            ],
            form: ["W", "L", "W", "L", "W"],
            teamImageId: 225644,
            teamQualifyStatus: "E",
          },
          {
            teamId: 966,
            teamName: "LSG",
            matchesPlayed: 14,
            matchesWon: 7,
            matchesLost: 7,
            points: 14,
            nrr: "-0.667",
            teamFullName: "Lucknow Super Giants",
            teamMatches: [
              {
                opponent: "Rajasthan Royals",
                startdt: "1711274400000",
                result: "Lost by 20 runs",
                opponentSName: "RR",
                matchId: 89668,
                matchName: "4th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1711807200000",
                result: "Won by 21 runs",
                opponentSName: "PBKS",
                matchId: 89710,
                matchName: "11th Match",
                winner: 966,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1712066400000",
                result: "Won by 28 runs",
                opponentSName: "RCB",
                matchId: 89738,
                matchName: "15th Match",
                winner: 966,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1712498400000",
                result: "Won by 33 runs",
                opponentSName: "GT",
                matchId: 89770,
                matchName: "21st Match",
                winner: 966,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1712930400000",
                result: "Lost by 6 wkts",
                opponentSName: "DC",
                matchId: 91407,
                matchName: "26th Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1713088800000",
                result: "Lost by 8 wkts",
                opponentSName: "KKR",
                matchId: 91420,
                matchName: "28th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1713535200000",
                result: "Won by 8 wkts",
                opponentSName: "CSK",
                matchId: 91470,
                matchName: "34th Match",
                winner: 966,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1713880800000",
                result: "Won by 6 wkts",
                opponentSName: "CSK",
                matchId: 91506,
                matchName: "39th Match",
                winner: 966,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1714226400000",
                result: "Lost by 7 wkts",
                opponentSName: "RR",
                matchId: 91542,
                matchName: "44th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1714485600000",
                result: "Won by 4 wkts",
                opponentSName: "MI",
                matchId: 91569,
                matchName: "48th Match",
                winner: 966,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1714917600000",
                result: "Lost by 98 runs",
                opponentSName: "KKR",
                matchId: 91618,
                matchName: "54th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1715176800000",
                result: "Lost by 10 wkts",
                opponentSName: "SRH",
                matchId: 91641,
                matchName: "57th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1715695200000",
                result: "Lost by 19 runs",
                opponentSName: "DC",
                matchId: 91681,
                matchName: "64th Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1715954400000",
                result: "Won by 18 runs",
                opponentSName: "MI",
                matchId: 91699,
                matchName: "67th Match",
                winner: 966,
                opponentId: 62,
                opponentImageId: 225645,
              },
            ],
            form: ["W", "L", "L", "L", "W"],
            teamImageId: 389444,
            teamQualifyStatus: "E",
          },
          {
            teamId: 971,
            teamName: "GT",
            matchesPlayed: 14,
            matchesWon: 5,
            matchesLost: 7,
            noRes: 2,
            points: 12,
            nrr: "-1.063",
            teamFullName: "Gujarat Titans",
            teamMatches: [
              {
                opponent: "Mumbai Indians",
                startdt: "1711288800000",
                result: "Won by 6 runs",
                opponentSName: "MI",
                matchId: 89675,
                matchName: "5th Match",
                winner: 971,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1711461600000",
                result: "Lost by 63 runs",
                opponentSName: "CSK",
                matchId: 89689,
                matchName: "7th Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1711879200000",
                result: "Won by 7 wkts",
                opponentSName: "SRH",
                matchId: 89717,
                matchName: "12th Match",
                winner: 971,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1712239200000",
                result: "Lost by 3 wkts",
                opponentSName: "PBKS",
                matchId: 89749,
                matchName: "17th Match",
                winner: 65,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1712498400000",
                result: "Lost by 33 runs",
                opponentSName: "LSG",
                matchId: 89770,
                matchName: "21st Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1712757600000",
                result: "Won by 3 wkts",
                opponentSName: "RR",
                matchId: 91393,
                matchName: "24th Match",
                winner: 971,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1713362400000",
                result: "Lost by 6 wkts",
                opponentSName: "DC",
                matchId: 91452,
                matchName: "32nd Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1713708000000",
                result: "Won by 3 wkts",
                opponentSName: "PBKS",
                matchId: 91488,
                matchName: "37th Match",
                winner: 971,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1713967200000",
                result: "Lost by 4 runs",
                opponentSName: "DC",
                matchId: 91515,
                matchName: "40th Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1714298400000",
                result: "Lost by 9 wkts",
                opponentSName: "RCB",
                matchId: 91551,
                matchName: "45th Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1714831200000",
                result: "Lost by 4 wkts",
                opponentSName: "RCB",
                matchId: 91600,
                matchName: "52nd Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1715349600000",
                result: "Won by 35 runs",
                opponentSName: "CSK",
                matchId: 91650,
                matchName: "59th Match",
                winner: 971,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1715608800000",
                result: "Match abandoned without toss",
                opponentSName: "KKR",
                matchId: 91677,
                matchName: "63rd Match",
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1715868000000",
                result: "Match abandoned without toss",
                opponentSName: "SRH",
                matchId: 91690,
                matchName: "66th Match",
                opponentId: 255,
                opponentImageId: 225649,
              },
            ],
            form: ["L", "L", "W", "A", "A"],
            teamImageId: 235085,
            teamQualifyStatus: "E",
          },
          {
            teamId: 65,
            teamName: "PBKS",
            matchesPlayed: 14,
            matchesWon: 5,
            matchesLost: 9,
            points: 10,
            nrr: "-0.353",
            teamFullName: "Punjab Kings",
            teamMatches: [
              {
                opponent: "Delhi Capitals",
                startdt: "1711188000000",
                result: "Won by 4 wkts",
                opponentSName: "DC",
                matchId: 89661,
                matchName: "2nd Match",
                winner: 65,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1711375200000",
                result: "Lost by 4 wkts",
                opponentSName: "RCB",
                matchId: 89682,
                matchName: "6th Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1711807200000",
                result: "Lost by 21 runs",
                opponentSName: "LSG",
                matchId: 89710,
                matchName: "11th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1712239200000",
                result: "Won by 3 wkts",
                opponentSName: "GT",
                matchId: 89749,
                matchName: "17th Match",
                winner: 65,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1712671200000",
                result: "Lost by 2 runs",
                opponentSName: "SRH",
                matchId: 91389,
                matchName: "23rd Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1713016800000",
                result: "Lost by 3 wkts",
                opponentSName: "RR",
                matchId: 91416,
                matchName: "27th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Mumbai Indians",
                startdt: "1713448800000",
                result: "Lost by 9 runs",
                opponentSName: "MI",
                matchId: 91461,
                matchName: "33rd Match",
                winner: 62,
                opponentId: 62,
                opponentImageId: 225645,
              },
              {
                opponent: "Gujarat Titans",
                startdt: "1713708000000",
                result: "Lost by 3 wkts",
                opponentSName: "GT",
                matchId: 91488,
                matchName: "37th Match",
                winner: 971,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1714140000000",
                result: "Won by 8 wkts",
                opponentSName: "KKR",
                matchId: 91528,
                matchName: "42nd Match",
                winner: 65,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1714572000000",
                result: "Won by 7 wkts",
                opponentSName: "CSK",
                matchId: 91578,
                matchName: "49th Match",
                winner: 65,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1714903200000",
                result: "Lost by 28 runs",
                opponentSName: "CSK",
                matchId: 91609,
                matchName: "53rd Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1715263200000",
                result: "Lost by 60 runs",
                opponentSName: "RCB",
                matchId: 91645,
                matchName: "58th Match",
                winner: 59,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1715781600000",
                result: "Won by 5 wkts",
                opponentSName: "RR",
                matchId: 91686,
                matchName: "65th Match",
                winner: 65,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1716112800000",
                result: "Lost by 4 wkts",
                opponentSName: "SRH",
                matchId: 91713,
                matchName: "69th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
            ],
            form: ["W", "L", "L", "W", "L"],
            teamImageId: 225648,
            teamQualifyStatus: "E",
          },
          {
            teamId: 62,
            teamName: "MI",
            matchesPlayed: 14,
            matchesWon: 4,
            matchesLost: 10,
            points: 8,
            nrr: "-0.318",
            teamFullName: "Mumbai Indians",
            teamMatches: [
              {
                opponent: "Gujarat Titans",
                startdt: "1711288800000",
                result: "Lost by 6 runs",
                opponentSName: "GT",
                matchId: 89675,
                matchName: "5th Match",
                winner: 971,
                opponentId: 971,
                opponentImageId: 235085,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1711548000000",
                result: "Lost by 31 runs",
                opponentSName: "SRH",
                matchId: 89693,
                matchName: "8th Match",
                winner: 255,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1711980000000",
                result: "Lost by 6 wkts",
                opponentSName: "RR",
                matchId: 89731,
                matchName: "14th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1712484000000",
                result: "Won by 29 runs",
                opponentSName: "DC",
                matchId: 89763,
                matchName: "20th Match",
                winner: 62,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Royal Challengers Bengaluru",
                startdt: "1712844000000",
                result: "Won by 7 wkts",
                opponentSName: "RCB",
                matchId: 91398,
                matchName: "25th Match",
                winner: 62,
                opponentId: 59,
                opponentImageId: 225643,
              },
              {
                opponent: "Chennai Super Kings",
                startdt: "1713103200000",
                result: "Lost by 20 runs",
                opponentSName: "CSK",
                matchId: 91425,
                matchName: "29th Match",
                winner: 58,
                opponentId: 58,
                opponentImageId: 225641,
              },
              {
                opponent: "Punjab Kings",
                startdt: "1713448800000",
                result: "Won by 9 runs",
                opponentSName: "PBKS",
                matchId: 91461,
                matchName: "33rd Match",
                winner: 62,
                opponentId: 65,
                opponentImageId: 225648,
              },
              {
                opponent: "Rajasthan Royals",
                startdt: "1713794400000",
                result: "Lost by 9 wkts",
                opponentSName: "RR",
                matchId: 91497,
                matchName: "38th Match",
                winner: 64,
                opponentId: 64,
                opponentImageId: 225647,
              },
              {
                opponent: "Delhi Capitals",
                startdt: "1714212000000",
                result: "Lost by 10 runs",
                opponentSName: "DC",
                matchId: 91533,
                matchName: "43rd Match",
                winner: 61,
                opponentId: 61,
                opponentImageId: 225644,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1714485600000",
                result: "Lost by 4 wkts",
                opponentSName: "LSG",
                matchId: 91569,
                matchName: "48th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1714744800000",
                result: "Lost by 24 runs",
                opponentSName: "KKR",
                matchId: 91596,
                matchName: "51st Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Sunrisers Hyderabad",
                startdt: "1715004000000",
                result: "Won by 7 wkts",
                opponentSName: "SRH",
                matchId: 91623,
                matchName: "55th Match",
                winner: 62,
                opponentId: 255,
                opponentImageId: 225649,
              },
              {
                opponent: "Kolkata Knight Riders",
                startdt: "1715436000000",
                result: "Lost by 18 runs - 16 overs game - due to rain",
                opponentSName: "KKR",
                matchId: 91654,
                matchName: "60th Match",
                winner: 63,
                opponentId: 63,
                opponentImageId: 225646,
              },
              {
                opponent: "Lucknow Super Giants",
                startdt: "1715954400000",
                result: "Lost by 18 runs",
                opponentSName: "LSG",
                matchId: 91699,
                matchName: "67th Match",
                winner: 966,
                opponentId: 966,
                opponentImageId: 389444,
              },
            ],
            form: ["L", "L", "W", "L", "L"],
            teamImageId: 225645,
            teamQualifyStatus: "E",
          },
        ],
      },
    ],
    appIndex: {
      seoTitle: "Indian Premier League 2024 Points Table | Cricbuzz.com",
      webURL:
        "www.cricbuzz.com/cricket-series/7607/indian-premier-league-2024/points-table",
    },
  };

  let [tableData, setTableData] = useState(
    pointsTableData.pointsTable[0].pointsTableInfo
  );

  // Get team colors based on team name
  const getTeamColors = (teamName) => {
    const colors = {
      'CSK': 'from-yellow-500 to-yellow-600',
      'RCB': 'from-red-500 to-red-600',
      'MI': 'from-blue-500 to-blue-600',
      'KKR': 'from-purple-500 to-purple-600',
      'DC': 'from-blue-400 to-blue-500',
      'PBKS': 'from-red-400 to-red-500',
      'RR': 'from-pink-500 to-pink-600',
      'SRH': 'from-orange-500 to-orange-600',
      'GT': 'from-gray-500 to-gray-600',
      'LSG': 'from-green-500 to-green-600'
    };
    return colors[teamName] || 'from-gray-500 to-gray-600';
  };

  const getTeamTextColors = (teamName) => {
    const colors = {
      'CSK': 'text-yellow-400',
      'RCB': 'text-red-400',
      'MI': 'text-blue-400',
      'KKR': 'text-purple-400',
      'DC': 'text-blue-300',
      'PBKS': 'text-red-300',
      'RR': 'text-pink-400',
      'SRH': 'text-orange-400',
      'GT': 'text-gray-400',
      'LSG': 'text-green-400'
    };
    return colors[teamName] || 'text-gray-400';
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-900 via-gray-800 to-black relative overflow-hidden">
      {/* Background elements */}
      <div className="absolute inset-0 overflow-hidden">
        <div className="absolute -top-40 -right-40 w-80 h-80 bg-gradient-to-br from-orange-500/10 to-red-500/10 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute -bottom-40 -left-40 w-80 h-80 bg-gradient-to-tr from-blue-500/10 to-purple-500/10 rounded-full blur-3xl animate-pulse delay-1000"></div>
      </div>

      <div className="relative z-10 max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
        {/* Header */}
        <div className="text-center mb-12 animate-fade-in">
          <h1 className="text-3xl sm:text-4xl lg:text-5xl font-bold bg-gradient-to-r from-orange-400 via-red-500 to-yellow-500 bg-clip-text text-transparent mb-4 animate-gradient">
            IPL 2024 Points Table
          </h1>
          <p className="text-gray-300 text-lg sm:text-xl font-light">
            Team Standings • Match Statistics • Performance Analysis
          </p>
          <div className="w-24 h-1 bg-gradient-to-r from-orange-500 to-red-500 mx-auto mt-4 rounded-full"></div>
        </div>

        {/* Points Table */}
        <div className="bg-gray-800/50 backdrop-blur-sm border border-gray-700/50 rounded-2xl overflow-hidden shadow-2xl animate-slide-up">
          {/* Table Header */}
          <div className="bg-gradient-to-r from-gray-700/50 to-gray-600/50 px-4 sm:px-6 py-4 border-b border-gray-600/50">
            <div className="grid grid-cols-8 gap-2 sm:gap-4 text-xs sm:text-sm font-semibold text-gray-300">
              <div className="text-center">#</div>
              <div className="text-left">Team</div>
              <div className="text-center hidden sm:block">Matches</div>
              <div className="text-center hidden sm:block">Won</div>
              <div className="text-center hidden sm:block">Lost</div>
              <div className="text-center">NRR</div>
              <div className="text-center">Points</div>
              <div className="text-center">Form</div>
            </div>
          </div>

          {/* Table Body */}
          <div className="divide-y divide-gray-700/50">
            {tableData.map(
              (
                {
                  form,
                  matchesLost,
                  matchesPlayed,
                  matchesWon,
                  teamName,
                  nrr,
                  points,
                  teamQualifyStatus,
                },
                i
              ) => (
                <div 
                  key={i} 
                  className={`group px-4 sm:px-6 py-4 hover:bg-gray-700/30 transition-all duration-300 ${
                    i < 4 ? 'bg-gradient-to-r from-green-500/5 to-emerald-500/5' : ''
                  }`}
                  style={{ animationDelay: `${i * 100}ms` }}
                >
                  <div className="grid grid-cols-8 gap-2 sm:gap-4 items-center">
                    {/* Position */}
                    <div className="text-center">
                      <div className={`w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${
                        i < 4 
                          ? 'bg-gradient-to-r from-green-500 to-emerald-500 text-white' 
                          : 'bg-gray-600 text-gray-300'
                      }`}>
                        {i + 1}
                      </div>
                    </div>

                    {/* Team */}
                    <div className="flex items-center space-x-3">
                      <div className={`w-10 h-10 bg-gradient-to-br ${getTeamColors(teamName)} rounded-full flex items-center justify-center shadow-lg`}>
                        <span className="text-white font-bold text-xs">{teamName}</span>
                      </div>
                      <div>
                        <p className={`font-semibold ${getTeamTextColors(teamName)} group-hover:text-white transition-colors duration-300`}>
                          {teamName}
                        </p>
                        {teamQualifyStatus === 'Q' && (
                          <span className="text-xs bg-green-500/20 text-green-400 px-2 py-1 rounded-full">
                            Qualified
                          </span>
                        )}
                      </div>
                    </div>

                    {/* Matches Played */}
                    <div className="text-center text-gray-300 font-medium hidden sm:block">
                      {matchesPlayed}
                    </div>

                    {/* Matches Won */}
                    <div className="text-center text-green-400 font-semibold hidden sm:block">
                      {matchesWon}
                    </div>

                    {/* Matches Lost */}
                    <div className="text-center text-red-400 font-semibold hidden sm:block">
                      {matchesLost}
                    </div>

                    {/* NRR */}
                    <div className="text-center">
                      <span className={`px-2 py-1 rounded-full text-xs font-semibold ${
                        parseFloat(nrr) >= 0 
                          ? 'bg-green-500/20 text-green-400' 
                          : 'bg-red-500/20 text-red-400'
                      }`}>
                        {nrr}
                      </span>
                    </div>

                    {/* Points */}
                    <div className="text-center">
                      <span className="bg-gradient-to-r from-orange-500 to-red-500 text-white px-3 py-1 rounded-full text-sm font-bold">
                        {points}
                      </span>
                    </div>

                    {/* Form */}
                    <div className="flex justify-center space-x-1">
                      {form.slice().reverse().map((result, idx) => (
                        <div key={idx} className="w-6 h-6 rounded-full flex items-center justify-center">
                          {result === "W" ? (
                            <i className="fas fa-check text-green-400 text-xs"></i>
                          ) : result === "L" ? (
                            <i className="fas fa-times text-red-400 text-xs"></i>
                          ) : (
                            <i className="fas fa-minus text-gray-400 text-xs"></i>
                          )}
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              )
            )}
          </div>
        </div>

        {/* Legend */}
        <div className="mt-8 flex justify-center space-x-8 animate-fade-in">
          <div className="flex items-center space-x-2">
            <div className="w-3 h-3 bg-green-500 rounded-full"></div>
            <span className="text-gray-400 text-sm">Qualified for Playoffs</span>
          </div>
          <div className="flex items-center space-x-2">
            <div className="w-3 h-3 bg-orange-500 rounded-full"></div>
            <span className="text-gray-400 text-sm">Top 4 Teams</span>
          </div>
          <div className="flex items-center space-x-2">
            <div className="w-3 h-3 bg-gray-500 rounded-full"></div>
            <span className="text-gray-400 text-sm">Eliminated</span>
          </div>
        </div>

        {/* Footer */}
        <div className="text-center mt-16 animate-fade-in">
          <p className="text-gray-400 text-sm">
            Updated after all league matches • Playoffs qualification based on points and NRR
          </p>
        </div>
      </div>
    </div>
  );
}

export default PointsTable;
